Classlist
akashcraft/GradePlus pull request #39
Opened 2024-10-14 12:05 UTC by mafewer

## Problem Statement
This is the same PR as the draft from last week, just with the updated variables and such for Moaaz's table. Sorry about the wait.

## Solution
Given a course code, in this case 6400, you receive a JSON response which has the success, error, illegal field as usual, but also a list of the data associated with each student, that being their profilePictures, usernames, etc

## Testing
https://drive.google.com/file/d/1Mf8bGDslAvPUPuN3HYdw6M-woS4-dLEd/view?usp=drive_link

2024-10-14 17:26 UTC, akashcraft requested changes

2024-10-14 17:26 UTC, akashcraft commented on services/get-students.php
> +if ($authorize !== $sharedSecret) {
I do not see any inputs being received from front-end. This variable would be undefined. `$authorize` should be `$_POST["authorize"]`

2024-10-14 17:26 UTC, akashcraft commented on services/get-students.php
> +$conn = new mysqli($db_host, $db_user, $db_pass, $db_name);
Remove single use variables and directly put in values in `$conn`
```suggestion
$conn = new mysqli('localhost','gradeplusclient' , 'gradeplussql', 'gradeplus');
```

2024-10-14 17:26 UTC, akashcraft commented on services/get-students.php
> +$stmt->bind_param("s", $course_code);
Possible NPE

2024-10-15 22:11 UTC, mafewer commented
Updated video test too https://drive.google.com/file/d/1gQWg4WODnx5KQmkTjfBDxvGpHx19-xv4/view?usp=sharing

2024-10-15 23:28 UTC, akashcraft approved these changes
Excellent!

2024-10-16 16:38 UTC, MoaazElshabasy reviewed
Neat

2024-10-16 16:39 UTC, MoaazElshabasy approved these changes
Neat

2024-10-16 16:39 UTC, merged