"Custom sql microservice backend code"
akashcraft/GradePlus pull request #9
Opened 2024-09-23 19:24 UTC by ddolomount

## Problem Statement
A microservice is required so that we can send custom SQL commands from the admin page. 
## Solution
Created the custom-sql.php microservice to handle the custom SQL commands coming from the admin page. The code checks for the correct authentication then sends the SQL command to the database and returns a success if the command works. 
## Testing

Video of SQL commands being sent
https://github.com/user-attachments/assets/c70c8f06-855b-4fc6-8ca8-ab05330c13dd

The resulting database after the SQL command
![custom-sql-result](https://github.com/user-attachments/assets/df54b496-a511-442c-9b17-a2b1d536e92d)

2024-09-23 20:02 UTC, akashcraft requested changes

2024-09-23 20:02 UTC, akashcraft commented on services/custom-sql.php
> +    header("Loaction: illegal.php");
```suggestion
    header("Location: illegal.php");
```

2024-09-23 20:03 UTC, akashcraft commented
Awesome Job Dan!
Just a minor typo. If you want you could test that case by putting `http://localhost:3000/services/custom-sql.php` directly in URL. It should show the `illegal.php` page.

2024-09-24 00:37 UTC, akashcraft approved these changes

2024-09-24 01:29 UTC, jfbrown03 approved these changes

2024-09-24 01:29 UTC, merged